///////////////////////////////////////////////////////////
//  CoreWebForm.cs
//  Implementation of the Class CoreWebForm
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

namespace CTool.Builder.CSharp
{
    public class CoreWebForm : ICoreForm
    {
        public CoreWebForm()
        {
        }

        ~CoreWebForm()
        {
        }

        /// 
        /// <param name="codeTemplateId"></param>
        /// <param name="value"></param>
        public string GenAssignCode(int codeTemplateId, string value)
        {
            return "";
        }
    }
} //end CoreWebForm