///////////////////////////////////////////////////////////
//  DotNetMVCBuilder.cs
//  Implementation of the Class DotNetMVCBuilder
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

namespace CTool.Builder.CSharp
{
    public class DotNetMVCBuilder : IBuilder
    {
        public DotNetMVCBuilder()
        {
        }

        ~DotNetMVCBuilder()
        {
        }

        /// 
        /// <param name="appId"></param>
        public void BuildApp(int appId)
        {
        }

        /// 
        /// <param name="templateId"></param>
        public string BuildTemplate(int templateId)
        {
            return "";
        }

        /// 
        /// <param name="pageId"></param>
        /// <param name="nameSpace"></param>
        public void BuildPage(int pageId, string nameSpace)
        {
        }

        /// 
        /// <param name="pageId"></param>
        public string BuildCodeBehind(int pageId)
        {
            return "";
        }

        /// 
        /// <param name="pageId"></param>
        public string BuildJS(int pageId)
        {
            return "";
        }
    }
} //end DotNetMVCBuilder