using System.Collections.Generic;
 namespace cDict
{
    public class D
    {
        // 0:method, 1:table key, 2:view key, 3:table, 4:view, 5:main function 
		public static Dictionary<string, string[]> _a = new Dictionary<string, string[]>  { 
			//tbl_PT_Permission
			{"pGettbl_PT_Permission"     , new[]{"P", "0", "0" ,"tbl_PT_Permission", "tbl_PT_Permission_View", "tbl_PT_Permission"}},
			{"fGettbl_PT_Permission"     , new[]{"G", "0", "0" ,"tbl_PT_Permission", "tbl_PT_Permission_View", "tbl_PT_Permission"}},
			{"Inserttbl_PT_Permission"   , new[]{"I", "0", "0" ,"tbl_PT_Permission", "tbl_PT_Permission_View", "tbl_PT_Permission"}},
			{"Updatetbl_PT_Permission"   , new[]{"U", "0", "0" ,"tbl_PT_Permission", "tbl_PT_Permission_View", "tbl_PT_Permission"}},
			{"Removetbl_PT_Permission"   , new[]{"D", "0", "0" ,"tbl_PT_Permission", "tbl_PT_Permission_View", "tbl_PT_Permission"}},
			//tbl_PT_Group_Permission
			{"pGettbl_PT_Group_Permission"     , new[]{"P", "1", "1" ,"tbl_PT_Group_Permission", "tbl_PT_Group_Permission_View", "tbl_PT_Group_Permission"}},
			{"fGettbl_PT_Group_Permission"     , new[]{"G", "1", "1" ,"tbl_PT_Group_Permission", "tbl_PT_Group_Permission_View", "tbl_PT_Group_Permission"}},
			{"Inserttbl_PT_Group_Permission"   , new[]{"I", "1", "1" ,"tbl_PT_Group_Permission", "tbl_PT_Group_Permission_View", "tbl_PT_Group_Permission"}},
			{"Updatetbl_PT_Group_Permission"   , new[]{"U", "1", "1" ,"tbl_PT_Group_Permission", "tbl_PT_Group_Permission_View", "tbl_PT_Group_Permission"}},
			{"Removetbl_PT_Group_Permission"   , new[]{"D", "1", "1" ,"tbl_PT_Group_Permission", "tbl_PT_Group_Permission_View", "tbl_PT_Group_Permission"}},
			//lyt_PT_Manager
			{"pGetlyt_PT_Manager"     , new[]{"P", "2", "2" ,"lyt_PT_Manager", "lyt_PT_Manager_View", "lyt_PT_Manager"}},
			{"fGetlyt_PT_Manager"     , new[]{"G", "2", "2" ,"lyt_PT_Manager", "lyt_PT_Manager_View", "lyt_PT_Manager"}},
			{"Insertlyt_PT_Manager"   , new[]{"I", "2", "2" ,"lyt_PT_Manager", "lyt_PT_Manager_View", "lyt_PT_Manager"}},
			{"Updatelyt_PT_Manager"   , new[]{"U", "2", "2" ,"lyt_PT_Manager", "lyt_PT_Manager_View", "lyt_PT_Manager"}},
			{"Removelyt_PT_Manager"   , new[]{"D", "2", "2" ,"lyt_PT_Manager", "lyt_PT_Manager_View", "lyt_PT_Manager"}},
			//tbl_PT_Group
			{"pGettbl_PT_Group"     , new[]{"P", "3", "3" ,"tbl_PT_Group", "tbl_PT_Group_View", "tbl_PT_Group"}},
			{"fGettbl_PT_Group"     , new[]{"G", "3", "3" ,"tbl_PT_Group", "tbl_PT_Group_View", "tbl_PT_Group"}},
			{"Inserttbl_PT_Group"   , new[]{"I", "3", "3" ,"tbl_PT_Group", "tbl_PT_Group_View", "tbl_PT_Group"}},
			{"Updatetbl_PT_Group"   , new[]{"U", "3", "3" ,"tbl_PT_Group", "tbl_PT_Group_View", "tbl_PT_Group"}},
			{"Removetbl_PT_Group"   , new[]{"D", "3", "3" ,"tbl_PT_Group", "tbl_PT_Group_View", "tbl_PT_Group"}},
			//tbl_PaymentType
			{"pGettbl_PaymentType"     , new[]{"P", "4", "4" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"fGettbl_PaymentType"     , new[]{"G", "4", "4" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"Inserttbl_PaymentType"   , new[]{"I", "4", "4" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"Updatetbl_PaymentType"   , new[]{"U", "4", "4" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"Removetbl_PaymentType"   , new[]{"D", "4", "4" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			//tbl_PaymentStatus
			{"pGettbl_PaymentStatus"     , new[]{"P", "5", "5" ,"tbl_PaymentStatus", "tbl_PaymentStatus_View", "tbl_PaymentStatus"}},
			{"fGettbl_PaymentStatus"     , new[]{"G", "5", "5" ,"tbl_PaymentStatus", "tbl_PaymentStatus_View", "tbl_PaymentStatus"}},
			{"Inserttbl_PaymentStatus"   , new[]{"I", "5", "5" ,"tbl_PaymentStatus", "tbl_PaymentStatus_View", "tbl_PaymentStatus"}},
			{"Updatetbl_PaymentStatus"   , new[]{"U", "5", "5" ,"tbl_PaymentStatus", "tbl_PaymentStatus_View", "tbl_PaymentStatus"}},
			{"Removetbl_PaymentStatus"   , new[]{"D", "5", "5" ,"tbl_PaymentStatus", "tbl_PaymentStatus_View", "tbl_PaymentStatus"}},
			//tbl_TicketStatus
			{"pGettbl_TicketStatus"     , new[]{"P", "6", "6" ,"tbl_TicketStatus", "tbl_TicketStatus_View", "tbl_TicketStatus"}},
			{"fGettbl_TicketStatus"     , new[]{"G", "6", "6" ,"tbl_TicketStatus", "tbl_TicketStatus_View", "tbl_TicketStatus"}},
			{"Inserttbl_TicketStatus"   , new[]{"I", "6", "6" ,"tbl_TicketStatus", "tbl_TicketStatus_View", "tbl_TicketStatus"}},
			{"Updatetbl_TicketStatus"   , new[]{"U", "6", "6" ,"tbl_TicketStatus", "tbl_TicketStatus_View", "tbl_TicketStatus"}},
			{"Removetbl_TicketStatus"   , new[]{"D", "6", "6" ,"tbl_TicketStatus", "tbl_TicketStatus_View", "tbl_TicketStatus"}},
			//tbl_Taxi_Type
			{"pGettbl_Taxi_Type"     , new[]{"P", "7", "7" ,"tbl_Taxi_Type", "tbl_Taxi_Type_View", "tbl_Taxi_Type"}},
			{"fGettbl_Taxi_Type"     , new[]{"G", "7", "7" ,"tbl_Taxi_Type", "tbl_Taxi_Type_View", "tbl_Taxi_Type"}},
			{"Inserttbl_Taxi_Type"   , new[]{"I", "7", "7" ,"tbl_Taxi_Type", "tbl_Taxi_Type_View", "tbl_Taxi_Type"}},
			{"Updatetbl_Taxi_Type"   , new[]{"U", "7", "7" ,"tbl_Taxi_Type", "tbl_Taxi_Type_View", "tbl_Taxi_Type"}},
			{"Removetbl_Taxi_Type"   , new[]{"D", "7", "7" ,"tbl_Taxi_Type", "tbl_Taxi_Type_View", "tbl_Taxi_Type"}},
			//tbl_Ticket
			{"pGettbl_Ticket"     , new[]{"P", "8", "8" ,"tbl_Ticket", "tbl_Ticket_View", "tbl_Ticket"}},
			{"fGettbl_Ticket"     , new[]{"G", "8", "8" ,"tbl_Ticket", "tbl_Ticket_View", "tbl_Ticket"}},
			{"Inserttbl_Ticket"   , new[]{"I", "8", "8" ,"tbl_Ticket", "tbl_Ticket_View", "tbl_Ticket"}},
			{"Updatetbl_Ticket"   , new[]{"U", "8", "8" ,"tbl_Ticket", "tbl_Ticket_View", "tbl_Ticket"}},
			{"Removetbl_Ticket"   , new[]{"D", "8", "8" ,"tbl_Ticket", "tbl_Ticket_View", "tbl_Ticket"}},
			//tbl_Driver
			{"pGettbl_Driver"     , new[]{"P", "9", "9" ,"tbl_Driver", "tbl_Driver_View", "tbl_Driver"}},
			{"fGettbl_Driver"     , new[]{"G", "9", "9" ,"tbl_Driver", "tbl_Driver_View", "tbl_Driver"}},
			{"Inserttbl_Driver"   , new[]{"I", "9", "9" ,"tbl_Driver", "tbl_Driver_View", "tbl_Driver"}},
			{"Updatetbl_Driver"   , new[]{"U", "9", "9" ,"tbl_Driver", "tbl_Driver_View", "tbl_Driver"}},
			{"Removetbl_Driver"   , new[]{"D", "9", "9" ,"tbl_Driver", "tbl_Driver_View", "tbl_Driver"}},
		};
        //[int: 1; float: 2; string: 4; date: 5; bool: 3] [0:type, 1:isnull, 2:key, 3:fkey, 4:length, 5:ftable, 6:fId, 7:Name]
		public static Dictionary<int, string[][]> _fd = new Dictionary<int, string[][]> { 
			{0, new [] {  //tbl_PT_Permission - 11 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "Module" },
				 new []{ "12", "1", "0", "", "512", "", "", "Description" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{1, new [] {  //tbl_PT_Group_Permission - 12 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "GroupId" },
				 new []{ "8", "1", "0", "", "4", "", "", "PermissionId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "Description" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{2, new [] {  //lyt_PT_Manager - 18 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "GroupId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "22", "1", "0", "", "128", "", "", "UserName" },
				 new []{ "12", "1", "0", "", "512", "", "", "Password" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "FullName" },
				 new []{ "22", "1", "0", "", "128", "", "", "PrimaryPhone" },
				 new []{ "22", "1", "0", "", "128", "", "", "PrimaryEmail" },
				 new []{ "12", "1", "0", "", "512", "", "", "Address" },
				 new []{ "8", "1", "0", "", "4", "", "", "ProvinceId" },
				 new []{ "22", "1", "0", "", "128", "", "", "AreaCode" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{3, new [] {  //tbl_PT_Group - 11 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "Description" },
				 new []{ "22", "1", "0", "", "50", "", "", "Color" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{4, new [] {  //tbl_PaymentType - 9 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{5, new [] {  //tbl_PaymentStatus - 9 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{6, new [] {  //tbl_TicketStatus - 9 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{7, new [] {  //tbl_Taxi_Type - 9 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{8, new [] {  //tbl_Ticket - 41 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "CustId" },
				 new []{ "8", "1", "0", "", "4", "", "", "DriverId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "CustName" },
				 new []{ "22", "1", "0", "", "128", "", "", "CustEmail" },
				 new []{ "22", "1", "0", "", "128", "", "", "CustMobile" },
				 new []{ "12", "1", "0", "", "512", "", "", "DriverName" },
				 new []{ "22", "1", "0", "", "128", "", "", "DriverMobile" },
				 new []{ "4", "1", "0", "", "8", "", "", "DepartureDate" },
				 new []{ "22", "1", "0", "", "50", "", "", "DepatureTime" },
				 new []{ "6", "1", "0", "", "8", "", "", "SrcLat" },
				 new []{ "6", "1", "0", "", "8", "", "", "SrcLng" },
				 new []{ "6", "1", "0", "", "8", "", "", "DestLat" },
				 new []{ "6", "1", "0", "", "8", "", "", "DestLng" },
				 new []{ "12", "1", "0", "", "512", "", "", "SrcAddr" },
				 new []{ "12", "1", "0", "", "512", "", "", "DestAddr" },
				 new []{ "8", "1", "0", "", "4", "", "", "TaxiType" },
				 new []{ "8", "1", "0", "", "4", "", "", "Price" },
				 new []{ "6", "1", "0", "", "8", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "SubTotal" },
				 new []{ "8", "1", "0", "", "4", "", "", "Discount" },
				 new []{ "8", "1", "0", "", "4", "", "", "Surcharge" },
				 new []{ "8", "1", "0", "", "4", "", "", "Total" },
				 new []{ "22", "1", "0", "", "128", "", "", "PromoCode" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "8", "1", "0", "", "4", "", "", "PaymentStatus" },
				 new []{ "8", "1", "0", "", "4", "", "", "PaymentType" },
				 new []{ "8", "1", "0", "", "4", "", "", "MailStatus" },
				 new []{ "8", "1", "0", "", "4", "", "", "SMSStatus" },
				 new []{ "22", "1", "0", "", "128", "", "", "SMSRefId" },
				 new []{ "4", "1", "0", "", "8", "", "", "ExpiredTime" },
				 new []{ "22", "1", "0", "", "128", "", "", "SessionId" },
				 new []{ "22", "1", "0", "", "128", "", "", "ClientIP" },
				 new []{ "22", "1", "0", "", "128", "", "", "ClientApp" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{9, new [] {  //tbl_Driver - 20 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "22", "1", "0", "", "128", "", "", "UserName" },
				 new []{ "12", "1", "0", "", "512", "", "", "Password" },
				 new []{ "12", "1", "0", "", "512", "", "", "FullName" },
				 new []{ "22", "1", "0", "", "128", "", "", "PrimaryPhone" },
				 new []{ "22", "1", "0", "", "128", "", "", "PrimaryEmail" },
				 new []{ "12", "1", "0", "", "512", "", "", "Address" },
				 new []{ "8", "1", "0", "", "4", "", "", "ProvinceId" },
				 new []{ "8", "1", "0", "", "4", "", "", "CityId" },
				 new []{ "8", "1", "0", "", "4", "", "", "TaxiType" },
				 new []{ "22", "1", "0", "", "128", "", "", "Number" },
				 new []{ "6", "1", "0", "", "8", "", "", "Latitude" },
				 new []{ "6", "1", "0", "", "8", "", "", "Longitude" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
		};
    }
}