using System.Collections.Generic;
 namespace cDict
{
    public class D
    {
        // 0:method, 1:table key, 2:view key, 3:table, 4:view, 5:main function 
		public static Dictionary<string, string[]> _a = new Dictionary<string, string[]>  { 
			//tbl_Departure
			{"pGettbl_Departure"     , new[]{"P", "0", "0" ,"tbl_Departure", "tbl_Departure_View", "tbl_Departure"}},
			{"fGettbl_Departure"     , new[]{"G", "0", "0" ,"tbl_Departure", "tbl_Departure_View", "tbl_Departure"}},
			{"Inserttbl_Departure"   , new[]{"I", "0", "0" ,"tbl_Departure", "tbl_Departure_View", "tbl_Departure"}},
			{"Updatetbl_Departure"   , new[]{"U", "0", "0" ,"tbl_Departure", "tbl_Departure_View", "tbl_Departure"}},
			{"Removetbl_Departure"   , new[]{"D", "0", "0" ,"tbl_Departure", "tbl_Departure_View", "tbl_Departure"}},
			//tbl_Route_Code
			{"pGettbl_Route_Code"     , new[]{"P", "1", "1" ,"tbl_Route_Code", "tbl_Route_Code_View", "tbl_Route_Code"}},
			{"fGettbl_Route_Code"     , new[]{"G", "1", "1" ,"tbl_Route_Code", "tbl_Route_Code_View", "tbl_Route_Code"}},
			{"Inserttbl_Route_Code"   , new[]{"I", "1", "1" ,"tbl_Route_Code", "tbl_Route_Code_View", "tbl_Route_Code"}},
			{"Updatetbl_Route_Code"   , new[]{"U", "1", "1" ,"tbl_Route_Code", "tbl_Route_Code_View", "tbl_Route_Code"}},
			{"Removetbl_Route_Code"   , new[]{"D", "1", "1" ,"tbl_Route_Code", "tbl_Route_Code_View", "tbl_Route_Code"}},
			//tbl_Bank
			{"pGettbl_Bank"     , new[]{"P", "2", "2" ,"tbl_Bank", "tbl_Bank_View", "tbl_Bank"}},
			{"fGettbl_Bank"     , new[]{"G", "2", "2" ,"tbl_Bank", "tbl_Bank_View", "tbl_Bank"}},
			{"Inserttbl_Bank"   , new[]{"I", "2", "2" ,"tbl_Bank", "tbl_Bank_View", "tbl_Bank"}},
			{"Updatetbl_Bank"   , new[]{"U", "2", "2" ,"tbl_Bank", "tbl_Bank_View", "tbl_Bank"}},
			{"Removetbl_Bank"   , new[]{"D", "2", "2" ,"tbl_Bank", "tbl_Bank_View", "tbl_Bank"}},
			//tbl_Area
			{"pGettbl_Area"     , new[]{"P", "3", "3" ,"tbl_Area", "tbl_Area_View", "tbl_Area"}},
			{"fGettbl_Area"     , new[]{"G", "3", "3" ,"tbl_Area", "tbl_Area_View", "tbl_Area"}},
			{"Inserttbl_Area"   , new[]{"I", "3", "3" ,"tbl_Area", "tbl_Area_View", "tbl_Area"}},
			{"Updatetbl_Area"   , new[]{"U", "3", "3" ,"tbl_Area", "tbl_Area_View", "tbl_Area"}},
			{"Removetbl_Area"   , new[]{"D", "3", "3" ,"tbl_Area", "tbl_Area_View", "tbl_Area"}},
			//tbl_Route_SoldOut
			{"pGettbl_Route_SoldOut"     , new[]{"P", "4", "4" ,"tbl_Route_SoldOut", "tbl_Route_SoldOut_View", "tbl_Route_SoldOut"}},
			{"fGettbl_Route_SoldOut"     , new[]{"G", "4", "4" ,"tbl_Route_SoldOut", "tbl_Route_SoldOut_View", "tbl_Route_SoldOut"}},
			{"Inserttbl_Route_SoldOut"   , new[]{"I", "4", "4" ,"tbl_Route_SoldOut", "tbl_Route_SoldOut_View", "tbl_Route_SoldOut"}},
			{"Updatetbl_Route_SoldOut"   , new[]{"U", "4", "4" ,"tbl_Route_SoldOut", "tbl_Route_SoldOut_View", "tbl_Route_SoldOut"}},
			{"Removetbl_Route_SoldOut"   , new[]{"D", "4", "4" ,"tbl_Route_SoldOut", "tbl_Route_SoldOut_View", "tbl_Route_SoldOut"}},
			//tbl_PaymentType
			{"pGettbl_PaymentType"     , new[]{"P", "5", "5" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"fGettbl_PaymentType"     , new[]{"G", "5", "5" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"Inserttbl_PaymentType"   , new[]{"I", "5", "5" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"Updatetbl_PaymentType"   , new[]{"U", "5", "5" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			{"Removetbl_PaymentType"   , new[]{"D", "5", "5" ,"tbl_PaymentType", "tbl_PaymentType_View", "tbl_PaymentType"}},
			//tbl_PaymentType_Detail
			{"pGettbl_PaymentType_Detail"     , new[]{"P", "6", "6" ,"tbl_PaymentType_Detail", "tbl_PaymentType_Detail_View", "tbl_PaymentType_Detail"}},
			{"fGettbl_PaymentType_Detail"     , new[]{"G", "6", "6" ,"tbl_PaymentType_Detail", "tbl_PaymentType_Detail_View", "tbl_PaymentType_Detail"}},
			{"Inserttbl_PaymentType_Detail"   , new[]{"I", "6", "6" ,"tbl_PaymentType_Detail", "tbl_PaymentType_Detail_View", "tbl_PaymentType_Detail"}},
			{"Updatetbl_PaymentType_Detail"   , new[]{"U", "6", "6" ,"tbl_PaymentType_Detail", "tbl_PaymentType_Detail_View", "tbl_PaymentType_Detail"}},
			{"Removetbl_PaymentType_Detail"   , new[]{"D", "6", "6" ,"tbl_PaymentType_Detail", "tbl_PaymentType_Detail_View", "tbl_PaymentType_Detail"}},
			//tbl_PromotionCode
			{"pGettbl_PromotionCode"     , new[]{"P", "7", "7" ,"tbl_PromotionCode", "tbl_PromotionCode_View", "tbl_PromotionCode"}},
			{"fGettbl_PromotionCode"     , new[]{"G", "7", "7" ,"tbl_PromotionCode", "tbl_PromotionCode_View", "tbl_PromotionCode"}},
			{"Inserttbl_PromotionCode"   , new[]{"I", "7", "7" ,"tbl_PromotionCode", "tbl_PromotionCode_View", "tbl_PromotionCode"}},
			{"Updatetbl_PromotionCode"   , new[]{"U", "7", "7" ,"tbl_PromotionCode", "tbl_PromotionCode_View", "tbl_PromotionCode"}},
			{"Removetbl_PromotionCode"   , new[]{"D", "7", "7" ,"tbl_PromotionCode", "tbl_PromotionCode_View", "tbl_PromotionCode"}},
			//tbl_Branch
			{"pGettbl_Branch"     , new[]{"P", "8", "8" ,"tbl_Branch", "tbl_Branch_View", "tbl_Branch"}},
			{"fGettbl_Branch"     , new[]{"G", "8", "8" ,"tbl_Branch", "tbl_Branch_View", "tbl_Branch"}},
			{"Inserttbl_Branch"   , new[]{"I", "8", "8" ,"tbl_Branch", "tbl_Branch_View", "tbl_Branch"}},
			{"Updatetbl_Branch"   , new[]{"U", "8", "8" ,"tbl_Branch", "tbl_Branch_View", "tbl_Branch"}},
			{"Removetbl_Branch"   , new[]{"D", "8", "8" ,"tbl_Branch", "tbl_Branch_View", "tbl_Branch"}},
			//tbl_Report_AllBranchByDate
			{"pGettbl_Report_AllBranchByDate"     , new[]{"P", "9", "9" ,"tbl_Report_AllBranchByDate", "tbl_Report_AllBranchByDate_View", "tbl_Report_AllBranchByDate"}},
			{"fGettbl_Report_AllBranchByDate"     , new[]{"G", "9", "9" ,"tbl_Report_AllBranchByDate", "tbl_Report_AllBranchByDate_View", "tbl_Report_AllBranchByDate"}},
			{"Inserttbl_Report_AllBranchByDate"   , new[]{"I", "9", "9" ,"tbl_Report_AllBranchByDate", "tbl_Report_AllBranchByDate_View", "tbl_Report_AllBranchByDate"}},
			{"Updatetbl_Report_AllBranchByDate"   , new[]{"U", "9", "9" ,"tbl_Report_AllBranchByDate", "tbl_Report_AllBranchByDate_View", "tbl_Report_AllBranchByDate"}},
			{"Removetbl_Report_AllBranchByDate"   , new[]{"D", "9", "9" ,"tbl_Report_AllBranchByDate", "tbl_Report_AllBranchByDate_View", "tbl_Report_AllBranchByDate"}},
			//tbl_Report_Scheduler
			{"pGettbl_Report_Scheduler"     , new[]{"P", "10", "10" ,"tbl_Report_Scheduler", "tbl_Report_Scheduler_View", "tbl_Report_Scheduler"}},
			{"fGettbl_Report_Scheduler"     , new[]{"G", "10", "10" ,"tbl_Report_Scheduler", "tbl_Report_Scheduler_View", "tbl_Report_Scheduler"}},
			{"Inserttbl_Report_Scheduler"   , new[]{"I", "10", "10" ,"tbl_Report_Scheduler", "tbl_Report_Scheduler_View", "tbl_Report_Scheduler"}},
			{"Updatetbl_Report_Scheduler"   , new[]{"U", "10", "10" ,"tbl_Report_Scheduler", "tbl_Report_Scheduler_View", "tbl_Report_Scheduler"}},
			{"Removetbl_Report_Scheduler"   , new[]{"D", "10", "10" ,"tbl_Report_Scheduler", "tbl_Report_Scheduler_View", "tbl_Report_Scheduler"}},
			//tbl_GA_DatetimeQuerry
			{"pGettbl_GA_DatetimeQuerry"     , new[]{"P", "11", "11" ,"tbl_GA_DatetimeQuerry", "tbl_GA_DatetimeQuerry_View", "tbl_GA_DatetimeQuerry"}},
			{"fGettbl_GA_DatetimeQuerry"     , new[]{"G", "11", "11" ,"tbl_GA_DatetimeQuerry", "tbl_GA_DatetimeQuerry_View", "tbl_GA_DatetimeQuerry"}},
			{"Inserttbl_GA_DatetimeQuerry"   , new[]{"I", "11", "11" ,"tbl_GA_DatetimeQuerry", "tbl_GA_DatetimeQuerry_View", "tbl_GA_DatetimeQuerry"}},
			{"Updatetbl_GA_DatetimeQuerry"   , new[]{"U", "11", "11" ,"tbl_GA_DatetimeQuerry", "tbl_GA_DatetimeQuerry_View", "tbl_GA_DatetimeQuerry"}},
			{"Removetbl_GA_DatetimeQuerry"   , new[]{"D", "11", "11" ,"tbl_GA_DatetimeQuerry", "tbl_GA_DatetimeQuerry_View", "tbl_GA_DatetimeQuerry"}},
			//tbl_GA_UserLocationRegion
			{"pGettbl_GA_UserLocationRegion"     , new[]{"P", "12", "12" ,"tbl_GA_UserLocationRegion", "tbl_GA_UserLocationRegion_View", "tbl_GA_UserLocationRegion"}},
			{"fGettbl_GA_UserLocationRegion"     , new[]{"G", "12", "12" ,"tbl_GA_UserLocationRegion", "tbl_GA_UserLocationRegion_View", "tbl_GA_UserLocationRegion"}},
			{"Inserttbl_GA_UserLocationRegion"   , new[]{"I", "12", "12" ,"tbl_GA_UserLocationRegion", "tbl_GA_UserLocationRegion_View", "tbl_GA_UserLocationRegion"}},
			{"Updatetbl_GA_UserLocationRegion"   , new[]{"U", "12", "12" ,"tbl_GA_UserLocationRegion", "tbl_GA_UserLocationRegion_View", "tbl_GA_UserLocationRegion"}},
			{"Removetbl_GA_UserLocationRegion"   , new[]{"D", "12", "12" ,"tbl_GA_UserLocationRegion", "tbl_GA_UserLocationRegion_View", "tbl_GA_UserLocationRegion"}},
			//tbl_GA_App
			{"pGettbl_GA_App"     , new[]{"P", "13", "13" ,"tbl_GA_App", "tbl_GA_App_View", "tbl_GA_App"}},
			{"fGettbl_GA_App"     , new[]{"G", "13", "13" ,"tbl_GA_App", "tbl_GA_App_View", "tbl_GA_App"}},
			{"Inserttbl_GA_App"   , new[]{"I", "13", "13" ,"tbl_GA_App", "tbl_GA_App_View", "tbl_GA_App"}},
			{"Updatetbl_GA_App"   , new[]{"U", "13", "13" ,"tbl_GA_App", "tbl_GA_App_View", "tbl_GA_App"}},
			{"Removetbl_GA_App"   , new[]{"D", "13", "13" ,"tbl_GA_App", "tbl_GA_App_View", "tbl_GA_App"}},
			//tbl_GA_Ecommerce
			{"pGettbl_GA_Ecommerce"     , new[]{"P", "14", "14" ,"tbl_GA_Ecommerce", "tbl_GA_Ecommerce_View", "tbl_GA_Ecommerce"}},
			{"fGettbl_GA_Ecommerce"     , new[]{"G", "14", "14" ,"tbl_GA_Ecommerce", "tbl_GA_Ecommerce_View", "tbl_GA_Ecommerce"}},
			{"Inserttbl_GA_Ecommerce"   , new[]{"I", "14", "14" ,"tbl_GA_Ecommerce", "tbl_GA_Ecommerce_View", "tbl_GA_Ecommerce"}},
			{"Updatetbl_GA_Ecommerce"   , new[]{"U", "14", "14" ,"tbl_GA_Ecommerce", "tbl_GA_Ecommerce_View", "tbl_GA_Ecommerce"}},
			{"Removetbl_GA_Ecommerce"   , new[]{"D", "14", "14" ,"tbl_GA_Ecommerce", "tbl_GA_Ecommerce_View", "tbl_GA_Ecommerce"}},
			//tbl_GA_TicketCount
			{"pGettbl_GA_TicketCount"     , new[]{"P", "15", "15" ,"tbl_GA_TicketCount", "tbl_GA_TicketCount_View", "tbl_GA_TicketCount"}},
			{"fGettbl_GA_TicketCount"     , new[]{"G", "15", "15" ,"tbl_GA_TicketCount", "tbl_GA_TicketCount_View", "tbl_GA_TicketCount"}},
			{"Inserttbl_GA_TicketCount"   , new[]{"I", "15", "15" ,"tbl_GA_TicketCount", "tbl_GA_TicketCount_View", "tbl_GA_TicketCount"}},
			{"Updatetbl_GA_TicketCount"   , new[]{"U", "15", "15" ,"tbl_GA_TicketCount", "tbl_GA_TicketCount_View", "tbl_GA_TicketCount"}},
			{"Removetbl_GA_TicketCount"   , new[]{"D", "15", "15" ,"tbl_GA_TicketCount", "tbl_GA_TicketCount_View", "tbl_GA_TicketCount"}},
			//tbl_GA_User
			{"pGettbl_GA_User"     , new[]{"P", "16", "16" ,"tbl_GA_User", "tbl_GA_User_View", "tbl_GA_User"}},
			{"fGettbl_GA_User"     , new[]{"G", "16", "16" ,"tbl_GA_User", "tbl_GA_User_View", "tbl_GA_User"}},
			{"Inserttbl_GA_User"   , new[]{"I", "16", "16" ,"tbl_GA_User", "tbl_GA_User_View", "tbl_GA_User"}},
			{"Updatetbl_GA_User"   , new[]{"U", "16", "16" ,"tbl_GA_User", "tbl_GA_User_View", "tbl_GA_User"}},
			{"Removetbl_GA_User"   , new[]{"D", "16", "16" ,"tbl_GA_User", "tbl_GA_User_View", "tbl_GA_User"}},
			//tbl_Promotion
			{"pGettbl_Promotion"     , new[]{"P", "17", "17" ,"tbl_Promotion", "tbl_Promotion_View", "tbl_Promotion"}},
			{"fGettbl_Promotion"     , new[]{"G", "17", "17" ,"tbl_Promotion", "tbl_Promotion_View", "tbl_Promotion"}},
			{"Inserttbl_Promotion"   , new[]{"I", "17", "17" ,"tbl_Promotion", "tbl_Promotion_View", "tbl_Promotion"}},
			{"Updatetbl_Promotion"   , new[]{"U", "17", "17" ,"tbl_Promotion", "tbl_Promotion_View", "tbl_Promotion"}},
			{"Removetbl_Promotion"   , new[]{"D", "17", "17" ,"tbl_Promotion", "tbl_Promotion_View", "tbl_Promotion"}},
			//tbl_Report_TimeTableFullInfo
			{"pGettbl_Report_TimeTableFullInfo"     , new[]{"P", "18", "18" ,"tbl_Report_TimeTableFullInfo", "tbl_Report_TimeTableFullInfo_View", "tbl_Report_TimeTableFullInfo"}},
			{"fGettbl_Report_TimeTableFullInfo"     , new[]{"G", "18", "18" ,"tbl_Report_TimeTableFullInfo", "tbl_Report_TimeTableFullInfo_View", "tbl_Report_TimeTableFullInfo"}},
			{"Inserttbl_Report_TimeTableFullInfo"   , new[]{"I", "18", "18" ,"tbl_Report_TimeTableFullInfo", "tbl_Report_TimeTableFullInfo_View", "tbl_Report_TimeTableFullInfo"}},
			{"Updatetbl_Report_TimeTableFullInfo"   , new[]{"U", "18", "18" ,"tbl_Report_TimeTableFullInfo", "tbl_Report_TimeTableFullInfo_View", "tbl_Report_TimeTableFullInfo"}},
			{"Removetbl_Report_TimeTableFullInfo"   , new[]{"D", "18", "18" ,"tbl_Report_TimeTableFullInfo", "tbl_Report_TimeTableFullInfo_View", "tbl_Report_TimeTableFullInfo"}},
			//tbl_GA_CardCount
			{"pGettbl_GA_CardCount"     , new[]{"P", "19", "19" ,"tbl_GA_CardCount", "tbl_GA_CardCount_View", "tbl_GA_CardCount"}},
			{"fGettbl_GA_CardCount"     , new[]{"G", "19", "19" ,"tbl_GA_CardCount", "tbl_GA_CardCount_View", "tbl_GA_CardCount"}},
			{"Inserttbl_GA_CardCount"   , new[]{"I", "19", "19" ,"tbl_GA_CardCount", "tbl_GA_CardCount_View", "tbl_GA_CardCount"}},
			{"Updatetbl_GA_CardCount"   , new[]{"U", "19", "19" ,"tbl_GA_CardCount", "tbl_GA_CardCount_View", "tbl_GA_CardCount"}},
			{"Removetbl_GA_CardCount"   , new[]{"D", "19", "19" ,"tbl_GA_CardCount", "tbl_GA_CardCount_View", "tbl_GA_CardCount"}},
			//tbl_GA_Source
			{"pGettbl_GA_Source"     , new[]{"P", "20", "20" ,"tbl_GA_Source", "tbl_GA_Source_View", "tbl_GA_Source"}},
			{"fGettbl_GA_Source"     , new[]{"G", "20", "20" ,"tbl_GA_Source", "tbl_GA_Source_View", "tbl_GA_Source"}},
			{"Inserttbl_GA_Source"   , new[]{"I", "20", "20" ,"tbl_GA_Source", "tbl_GA_Source_View", "tbl_GA_Source"}},
			{"Updatetbl_GA_Source"   , new[]{"U", "20", "20" ,"tbl_GA_Source", "tbl_GA_Source_View", "tbl_GA_Source"}},
			{"Removetbl_GA_Source"   , new[]{"D", "20", "20" ,"tbl_GA_Source", "tbl_GA_Source_View", "tbl_GA_Source"}},
			//tbl_Route_Exclude
			{"pGettbl_Route_Exclude"     , new[]{"P", "21", "21" ,"tbl_Route_Exclude", "tbl_Route_Exclude_View", "tbl_Route_Exclude"}},
			{"fGettbl_Route_Exclude"     , new[]{"G", "21", "21" ,"tbl_Route_Exclude", "tbl_Route_Exclude_View", "tbl_Route_Exclude"}},
			{"Inserttbl_Route_Exclude"   , new[]{"I", "21", "21" ,"tbl_Route_Exclude", "tbl_Route_Exclude_View", "tbl_Route_Exclude"}},
			{"Updatetbl_Route_Exclude"   , new[]{"U", "21", "21" ,"tbl_Route_Exclude", "tbl_Route_Exclude_View", "tbl_Route_Exclude"}},
			{"Removetbl_Route_Exclude"   , new[]{"D", "21", "21" ,"tbl_Route_Exclude", "tbl_Route_Exclude_View", "tbl_Route_Exclude"}},
			//tbl_Route_Stop
			{"pGettbl_Route_Stop"     , new[]{"P", "22", "22" ,"tbl_Route_Stop", "tbl_Route_Stop_View", "tbl_Route_Stop"}},
			{"fGettbl_Route_Stop"     , new[]{"G", "22", "22" ,"tbl_Route_Stop", "tbl_Route_Stop_View", "tbl_Route_Stop"}},
			{"Inserttbl_Route_Stop"   , new[]{"I", "22", "22" ,"tbl_Route_Stop", "tbl_Route_Stop_View", "tbl_Route_Stop"}},
			{"Updatetbl_Route_Stop"   , new[]{"U", "22", "22" ,"tbl_Route_Stop", "tbl_Route_Stop_View", "tbl_Route_Stop"}},
			{"Removetbl_Route_Stop"   , new[]{"D", "22", "22" ,"tbl_Route_Stop", "tbl_Route_Stop_View", "tbl_Route_Stop"}},
			//tbl_Branch_Office
			{"pGettbl_Branch_Office"     , new[]{"P", "23", "23" ,"tbl_Branch_Office", "tbl_Branch_Office_View", "tbl_Branch_Office"}},
			{"fGettbl_Branch_Office"     , new[]{"G", "23", "23" ,"tbl_Branch_Office", "tbl_Branch_Office_View", "tbl_Branch_Office"}},
			{"Inserttbl_Branch_Office"   , new[]{"I", "23", "23" ,"tbl_Branch_Office", "tbl_Branch_Office_View", "tbl_Branch_Office"}},
			{"Updatetbl_Branch_Office"   , new[]{"U", "23", "23" ,"tbl_Branch_Office", "tbl_Branch_Office_View", "tbl_Branch_Office"}},
			{"Removetbl_Branch_Office"   , new[]{"D", "23", "23" ,"tbl_Branch_Office", "tbl_Branch_Office_View", "tbl_Branch_Office"}},
			//tbl_Route
			{"pGettbl_Route"     , new[]{"P", "24", "24" ,"tbl_Route", "tbl_Route_View", "tbl_Route"}},
			{"fGettbl_Route"     , new[]{"G", "24", "24" ,"tbl_Route", "tbl_Route_View", "tbl_Route"}},
			{"Inserttbl_Route"   , new[]{"I", "24", "24" ,"tbl_Route", "tbl_Route_View", "tbl_Route"}},
			{"Updatetbl_Route"   , new[]{"U", "24", "24" ,"tbl_Route", "tbl_Route_View", "tbl_Route"}},
			{"Removetbl_Route"   , new[]{"D", "24", "24" ,"tbl_Route", "tbl_Route_View", "tbl_Route"}},
			//tbl_Stop
			{"pGettbl_Stop"     , new[]{"P", "25", "25" ,"tbl_Stop", "tbl_Stop_View", "tbl_Stop"}},
			{"fGettbl_Stop"     , new[]{"G", "25", "25" ,"tbl_Stop", "tbl_Stop_View", "tbl_Stop"}},
			{"Inserttbl_Stop"   , new[]{"I", "25", "25" ,"tbl_Stop", "tbl_Stop_View", "tbl_Stop"}},
			{"Updatetbl_Stop"   , new[]{"U", "25", "25" ,"tbl_Stop", "tbl_Stop_View", "tbl_Stop"}},
			{"Removetbl_Stop"   , new[]{"D", "25", "25" ,"tbl_Stop", "tbl_Stop_View", "tbl_Stop"}},
			//tbl_ViFuta_Report
			{"pGettbl_ViFuta_Report"     , new[]{"P", "26", "26" ,"tbl_ViFuta_Report", "tbl_ViFuta_Report_View", "tbl_ViFuta_Report"}},
			{"fGettbl_ViFuta_Report"     , new[]{"G", "26", "26" ,"tbl_ViFuta_Report", "tbl_ViFuta_Report_View", "tbl_ViFuta_Report"}},
			{"Inserttbl_ViFuta_Report"   , new[]{"I", "26", "26" ,"tbl_ViFuta_Report", "tbl_ViFuta_Report_View", "tbl_ViFuta_Report"}},
			{"Updatetbl_ViFuta_Report"   , new[]{"U", "26", "26" ,"tbl_ViFuta_Report", "tbl_ViFuta_Report_View", "tbl_ViFuta_Report"}},
			{"Removetbl_ViFuta_Report"   , new[]{"D", "26", "26" ,"tbl_ViFuta_Report", "tbl_ViFuta_Report_View", "tbl_ViFuta_Report"}},
		};
        //[int: 1; float: 2; string: 4; date: 5; bool: 3] [0:type, 1:isnull, 2:key, 3:fkey, 4:length, 5:ftable, 6:fId, 7:Name]
		public static Dictionary<int, string[][]> _fd = new Dictionary<int, string[][]> { 
			{0, new [] {  //tbl_Departure - 21 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "ValidStartDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "ValidEndDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "ValidStartDateOffset" },
				 new []{ "8", "1", "0", "", "4", "", "", "MaxBookSeat" },
				 new []{ "22", "1", "0", "", "256", "", "", "EmailTemplateName" },
				 new []{ "22", "1", "0", "", "256", "", "", "SMSTemplateName" },
				 new []{ "22", "1", "0", "", "256", "", "", "PrePaidEmailTemplateName" },
				 new []{ "22", "1", "0", "", "256", "", "", "PrePaidSMSTemplateName" },
				 new []{ "22", "1", "0", "", "512", "", "", "ReturnSuccessUrlFormat" },
				 new []{ "22", "1", "0", "", "512", "", "", "ReturnErrorUrlFormat" },
				 new []{ "22", "1", "0", "", "128", "", "", "App" },
				 new []{ "12", "1", "0", "", "1024", "", "", "Meta" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{1, new [] {  //tbl_Route_Code - 14 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "0", "1", "0", "", "8", "", "", "RouteId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "OriginCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "OriginName" },
				 new []{ "22", "1", "0", "", "128", "", "", "DestCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "DestName" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{2, new [] {  //tbl_Bank - 11 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "BankType" },
				 new []{ "22", "1", "0", "", "128", "", "", "CssClass" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{3, new [] {  //tbl_Area - 10 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "0", "1", "0", "", "8", "", "", "BaseId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{4, new [] {  //tbl_Route_SoldOut - 12 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "RouteId" },
				 new []{ "4", "1", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "ToDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{5, new [] {  //tbl_PaymentType - 14 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "Description" },
				 new []{ "22", "1", "0", "", "512", "", "", "App" },
				 new []{ "8", "1", "0", "", "4", "", "", "Priority" },
				 new []{ "22", "1", "0", "", "50", "", "", "FromTime" },
				 new []{ "22", "1", "0", "", "50", "", "", "ToTime" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{6, new [] {  //tbl_PaymentType_Detail - 13 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "PaymentTypeId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "Number" },
				 new []{ "22", "1", "0", "", "128", "", "", "CssClass" },
				 new []{ "12", "1", "0", "", "512", "", "", "Description" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{7, new [] {  //tbl_PromotionCode - 11 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "ValidFromDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "ValidToDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{8, new [] {  //tbl_Branch - 9 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{9, new [] {  //tbl_Report_AllBranchByDate - 6 columns  
				 new []{ "8", "0", "1", "", "4", "", "", "IDRoute" },
				 new []{ "8", "0", "1", "", "4", "", "", "IDBranch" },
				 new []{ "8", "0", "1", "", "4", "", "", "IDOffice" },
				 new []{ "4", "0", "1", "", "8", "", "", "DateStart" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalTicket" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalMoney" },
			}},
			{10, new [] {  //tbl_Report_Scheduler - 2 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "4", "1", "0", "", "8", "", "", "FromDate" },
			}},
			{11, new [] {  //tbl_GA_DatetimeQuerry - 9 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "Startdate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{12, new [] {  //tbl_GA_UserLocationRegion - 74 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DatetimeQuerry" },
				 new []{ "12", "1", "0", "", "100", "", "", "TypeName" },
				 new []{ "8", "1", "0", "", "4", "", "", "AnGiang" },
				 new []{ "8", "1", "0", "", "4", "", "", "BaRia_VungTau" },
				 new []{ "8", "1", "0", "", "4", "", "", "BacGiang" },
				 new []{ "8", "1", "0", "", "4", "", "", "BacKan" },
				 new []{ "8", "1", "0", "", "4", "", "", "BacLieu" },
				 new []{ "8", "1", "0", "", "4", "", "", "BacNinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "BenTre" },
				 new []{ "8", "1", "0", "", "4", "", "", "BinhDinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "BinhPhuoc" },
				 new []{ "8", "1", "0", "", "4", "", "", "BinhThuan" },
				 new []{ "8", "1", "0", "", "4", "", "", "CaMau" },
				 new []{ "8", "1", "0", "", "4", "", "", "CanTho" },
				 new []{ "8", "1", "0", "", "4", "", "", "CaoBang" },
				 new []{ "8", "1", "0", "", "4", "", "", "DaNang" },
				 new []{ "8", "1", "0", "", "4", "", "", "DakNong" },
				 new []{ "8", "1", "0", "", "4", "", "", "DienBien" },
				 new []{ "8", "1", "0", "", "4", "", "", "DakLak" },
				 new []{ "8", "1", "0", "", "4", "", "", "DongThap" },
				 new []{ "8", "1", "0", "", "4", "", "", "DongNai" },
				 new []{ "8", "1", "0", "", "4", "", "", "GiaLai" },
				 new []{ "8", "1", "0", "", "4", "", "", "HaGiang" },
				 new []{ "8", "1", "0", "", "4", "", "", "HaNam" },
				 new []{ "8", "1", "0", "", "4", "", "", "HaTinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "HaiDuong" },
				 new []{ "8", "1", "0", "", "4", "", "", "HaiPhong" },
				 new []{ "8", "1", "0", "", "4", "", "", "HaNoi" },
				 new []{ "8", "1", "0", "", "4", "", "", "HauGiang" },
				 new []{ "8", "1", "0", "", "4", "", "", "HoChiMinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "HoaBinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "HungYen" },
				 new []{ "8", "1", "0", "", "4", "", "", "KhanhHoa" },
				 new []{ "8", "1", "0", "", "4", "", "", "KienGiang" },
				 new []{ "8", "1", "0", "", "4", "", "", "KonTum" },
				 new []{ "8", "1", "0", "", "4", "", "", "LaiChau" },
				 new []{ "8", "1", "0", "", "4", "", "", "LamDong" },
				 new []{ "8", "1", "0", "", "4", "", "", "LangSon" },
				 new []{ "8", "1", "0", "", "4", "", "", "LaoCai" },
				 new []{ "8", "1", "0", "", "4", "", "", "LongAn" },
				 new []{ "8", "1", "0", "", "4", "", "", "NamDinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "NgheAn" },
				 new []{ "8", "1", "0", "", "4", "", "", "NinhBinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "NinhThuan" },
				 new []{ "8", "1", "0", "", "4", "", "", "PhuTho" },
				 new []{ "8", "1", "0", "", "4", "", "", "PhuYen" },
				 new []{ "8", "1", "0", "", "4", "", "", "QuangBinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "QuangNam" },
				 new []{ "8", "1", "0", "", "4", "", "", "QuangNgai" },
				 new []{ "8", "1", "0", "", "4", "", "", "QuangTri" },
				 new []{ "8", "1", "0", "", "4", "", "", "SocTrang" },
				 new []{ "8", "1", "0", "", "4", "", "", "SonLa" },
				 new []{ "8", "1", "0", "", "4", "", "", "TayNinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "ThaiBinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "ThaiNguyen" },
				 new []{ "8", "1", "0", "", "4", "", "", "ThanhHoa" },
				 new []{ "8", "1", "0", "", "4", "", "", "ThuaThienHue" },
				 new []{ "8", "1", "0", "", "4", "", "", "TienGiang" },
				 new []{ "8", "1", "0", "", "4", "", "", "TraVinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "TuyenQuang" },
				 new []{ "8", "1", "0", "", "4", "", "", "VinhLong" },
				 new []{ "8", "1", "0", "", "4", "", "", "VinhPhuc" },
				 new []{ "8", "1", "0", "", "4", "", "", "YenBai" },
				 new []{ "8", "1", "0", "", "4", "", "", "BinhDuong" },
				 new []{ "8", "1", "0", "", "4", "", "", "QuangNinh" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{13, new [] {  //tbl_GA_App - 20 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DatetimeQuerry" },
				 new []{ "8", "1", "0", "", "4", "", "", "AndroidUser" },
				 new []{ "8", "1", "0", "", "4", "", "", "IosUser" },
				 new []{ "8", "1", "0", "", "4", "", "", "ANewVisitor" },
				 new []{ "8", "1", "0", "", "4", "", "", "AReturnVisitor" },
				 new []{ "8", "1", "0", "", "4", "", "", "INewVisitor" },
				 new []{ "8", "1", "0", "", "4", "", "", "IReturnVisitor" },
				 new []{ "8", "1", "0", "", "4", "", "", "ACountDownload" },
				 new []{ "8", "1", "0", "", "4", "", "", "ICountDownload" },
				 new []{ "12", "1", "0", "", "5", "", "", "AAvgTime" },
				 new []{ "12", "1", "0", "", "5", "", "", "IAvgTime" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{14, new [] {  //tbl_GA_Ecommerce - 21 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DatetimeQuerry" },
				 new []{ "8", "1", "0", "", "4", "", "", "Transactions" },
				 new []{ "8", "1", "0", "", "4", "", "", "Sessions" },
				 new []{ "6", "1", "0", "", "8", "", "", "TotalRevenue" },
				 new []{ "6", "1", "0", "", "8", "", "", "TransactionsPerSessions" },
				 new []{ "6", "1", "0", "", "8", "", "", "RevenuePerTransacsions" },
				 new []{ "8", "1", "0", "", "4", "", "", "ProductListViews" },
				 new []{ "8", "1", "0", "", "4", "", "", "ProductAddsToCart" },
				 new []{ "8", "1", "0", "", "4", "", "", "ProductCheckouts" },
				 new []{ "8", "1", "0", "", "4", "", "", "ItemQuantity" },
				 new []{ "8", "1", "0", "", "4", "", "", "QuantityAddsToCart" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
				 new []{ "12", "1", "0", "", "256", "", "", "Client" },
			}},
			{15, new [] {  //tbl_GA_TicketCount - 14 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DatetimeQuerry" },
				 new []{ "12", "1", "0", "", "-1", "", "", "ProductCategory" },
				 new []{ "6", "1", "0", "", "8", "", "", "ItemRevenue" },
				 new []{ "8", "1", "0", "", "4", "", "", "ItemQuantity" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
				 new []{ "12", "1", "0", "", "256", "", "", "Client" },
			}},
			{16, new [] {  //tbl_GA_User - 17 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DatetimeQuerry" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalUser" },
				 new []{ "8", "1", "0", "", "4", "", "", "DesktopUser" },
				 new []{ "8", "1", "0", "", "4", "", "", "MobileUser" },
				 new []{ "8", "1", "0", "", "4", "", "", "TabletUser" },
				 new []{ "8", "1", "0", "", "4", "", "", "NewVisitor" },
				 new []{ "8", "1", "0", "", "4", "", "", "ReturnVisitor" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
				 new []{ "12", "1", "0", "", "256", "", "", "Client" },
			}},
			{17, new [] {  //tbl_Promotion - 16 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "12", "1", "0", "", "1024", "", "", "Description" },
				 new []{ "4", "1", "0", "", "8", "", "", "ValidFromDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "ValidToDate" },
				 new []{ "12", "1", "0", "", "512", "", "", "Image" },
				 new []{ "12", "1", "0", "", "512", "", "", "AndroidImage" },
				 new []{ "12", "1", "0", "", "512", "", "", "IOSImage" },
				 new []{ "12", "1", "0", "", "1024", "", "", "Url" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{18, new [] {  //tbl_Report_TimeTableFullInfo - 13 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "ID" },
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "128", "", "", "Time" },
				 new []{ "12", "1", "0", "", "256", "", "", "Number" },
				 new []{ "12", "1", "0", "", "512", "", "", "FullName" },
				 new []{ "12", "1", "0", "", "256", "", "", "FirstName" },
				 new []{ "12", "1", "0", "", "256", "", "", "Phone" },
				 new []{ "12", "1", "0", "", "512", "", "", "FullName2" },
				 new []{ "12", "1", "0", "", "256", "", "", "FirstName2" },
				 new []{ "12", "1", "0", "", "256", "", "", "Phone2" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
			}},
			{19, new [] {  //tbl_GA_CardCount - 15 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DatetimeQuerry" },
				 new []{ "12", "1", "0", "", "256", "", "", "Client" },
				 new []{ "12", "1", "0", "", "256", "", "", "CardCode" },
				 new []{ "12", "1", "0", "", "256", "", "", "CardName" },
				 new []{ "8", "1", "0", "", "4", "", "", "Sessions" },
				 new []{ "8", "1", "0", "", "4", "", "", "Transactions" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{20, new [] {  //tbl_GA_Source - 15 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DatetimeQuerry" },
				 new []{ "12", "1", "0", "", "256", "", "", "Client" },
				 new []{ "12", "1", "0", "", "256", "", "", "Source" },
				 new []{ "8", "1", "0", "", "4", "", "", "Transactions" },
				 new []{ "8", "1", "0", "", "4", "", "", "ItemQuantity" },
				 new []{ "6", "1", "0", "", "8", "", "", "ItemRevenue" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{21, new [] {  //tbl_Route_Exclude - 11 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "RouteId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "DepartureDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{22, new [] {  //tbl_Route_Stop - 23 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "0", "1", "0", "", "8", "", "", "RouteId" },
				 new []{ "0", "1", "0", "", "8", "", "", "OfficeId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "OrderNumber" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "8", "1", "0", "", "4", "", "", "ShuttleBefore" },
				 new []{ "12", "1", "0", "", "1024", "", "", "Note" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
				 new []{ "22", "1", "0", "", "50", "", "", "DepartureTime" },
				 new []{ "4", "1", "0", "", "8", "", "", "DepartureDate" },
				 new []{ "12", "1", "0", "", "512", "", "", "Address" },
				 new []{ "22", "1", "0", "", "50", "", "", "Phone" },
				 new []{ "22", "1", "0", "", "50", "", "", "Fax" },
				 new []{ "6", "1", "0", "", "8", "", "", "Latitude" },
				 new []{ "6", "1", "0", "", "8", "", "", "Longitude" },
			}},
			{23, new [] {  //tbl_Branch_Office - 10 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "0", "1", "0", "", "8", "", "", "BranchId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{24, new [] {  //tbl_Route - 21 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "12", "1", "0", "", "256", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "OriginCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "OriginName" },
				 new []{ "22", "1", "0", "", "128", "", "", "DestCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "DestName" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "12", "1", "0", "", "256", "", "", "Kind" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSchedule" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "GroupId" },
				 new []{ "8", "1", "0", "", "4", "", "", "ReturnId" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartWorkingDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "StopWorkingDate" },
			}},
			{25, new [] {  //tbl_Stop - 23 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "RouteId" },
				 new []{ "8", "1", "0", "", "4", "", "", "WayId" },
				 new []{ "8", "1", "0", "", "4", "", "", "OfficeId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "Address" },
				 new []{ "22", "1", "0", "", "50", "", "", "Phone" },
				 new []{ "22", "1", "0", "", "50", "", "", "Fax" },
				 new []{ "6", "1", "0", "", "8", "", "", "Latitude" },
				 new []{ "6", "1", "0", "", "8", "", "", "Longitude" },
				 new []{ "8", "1", "0", "", "4", "", "", "OrderNumber" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "2", "1", "0", "", "1", "", "", "Passing" },
				 new []{ "8", "1", "0", "", "4", "", "", "ShuttleBefore" },
				 new []{ "12", "1", "0", "", "1024", "", "", "Note" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{26, new [] {  //tbl_ViFuta_Report - 17 columns  
				 new []{ "0", "0", "1", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "4", "1", "0", "", "8", "", "", "LastReportTime" },
				 new []{ "4", "1", "0", "", "8", "", "", "ReportTime" },
				 new []{ "0", "1", "0", "", "8", "", "", "LastBalance" },
				 new []{ "0", "1", "0", "", "8", "", "", "Balance" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalBooking" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalCharge" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalWithDraw" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalClose" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
		};
    }
}