using System.Collections.Generic;
 namespace cDict
{
    public class DE
    {
        // 0:method, 1:table key, 2:view key, 3:table, 4:view, 5:main function 
		public static Dictionary<string, string[]> _a = new Dictionary<string, string[]>  { 
			//tbl_Route_Stop_Exclude_View
			{"pGettbl_Route_Stop_Exclude_View"     , new[]{"P", "27", "27" ,"tbl_Route_Stop_Exclude_View", "tbl_Route_Stop_Exclude_View", "tbl_Route_Stop_Exclude_View"}},
			{"fGettbl_Route_Stop_Exclude_View"     , new[]{"G", "27", "27" ,"tbl_Route_Stop_Exclude_View", "tbl_Route_Stop_Exclude_View", "tbl_Route_Stop_Exclude_View"}},
			//tbl_Route_View_001
			{"pGettbl_Route_View_001"     , new[]{"P", "28", "28" ,"tbl_Route_View_001", "tbl_Route_View_001", "tbl_Route_View_001"}},
			{"fGettbl_Route_View_001"     , new[]{"G", "28", "28" ,"tbl_Route_View_001", "tbl_Route_View_001", "tbl_Route_View_001"}},
			//tbl_Report_AllBranchByDate_View_001
			{"pGettbl_Report_AllBranchByDate_View_001"     , new[]{"P", "29", "29" ,"tbl_Report_AllBranchByDate_View_001", "tbl_Report_AllBranchByDate_View_001", "tbl_Report_AllBranchByDate_View_001"}},
			{"fGettbl_Report_AllBranchByDate_View_001"     , new[]{"G", "29", "29" ,"tbl_Report_AllBranchByDate_View_001", "tbl_Report_AllBranchByDate_View_001", "tbl_Report_AllBranchByDate_View_001"}},
			//tbl_Report_AllBranchByDate_View_002
			{"pGettbl_Report_AllBranchByDate_View_002"     , new[]{"P", "30", "30" ,"tbl_Report_AllBranchByDate_View_002", "tbl_Report_AllBranchByDate_View_002", "tbl_Report_AllBranchByDate_View_002"}},
			{"fGettbl_Report_AllBranchByDate_View_002"     , new[]{"G", "30", "30" ,"tbl_Report_AllBranchByDate_View_002", "tbl_Report_AllBranchByDate_View_002", "tbl_Report_AllBranchByDate_View_002"}},
			//tbl_Report_AllBranchByDate_View_003
			{"pGettbl_Report_AllBranchByDate_View_003"     , new[]{"P", "31", "31" ,"tbl_Report_AllBranchByDate_View_003", "tbl_Report_AllBranchByDate_View_003", "tbl_Report_AllBranchByDate_View_003"}},
			{"fGettbl_Report_AllBranchByDate_View_003"     , new[]{"G", "31", "31" ,"tbl_Report_AllBranchByDate_View_003", "tbl_Report_AllBranchByDate_View_003", "tbl_Report_AllBranchByDate_View_003"}},
			//tbl_Report_AllBranchByDate_View_004
			{"pGettbl_Report_AllBranchByDate_View_004"     , new[]{"P", "32", "32" ,"tbl_Report_AllBranchByDate_View_004", "tbl_Report_AllBranchByDate_View_004", "tbl_Report_AllBranchByDate_View_004"}},
			{"fGettbl_Report_AllBranchByDate_View_004"     , new[]{"G", "32", "32" ,"tbl_Report_AllBranchByDate_View_004", "tbl_Report_AllBranchByDate_View_004", "tbl_Report_AllBranchByDate_View_004"}},
			//tbl_Report_TimeTableFullInfo_View_001
			{"pGettbl_Report_TimeTableFullInfo_View_001"     , new[]{"P", "33", "33" ,"tbl_Report_TimeTableFullInfo_View_001", "tbl_Report_TimeTableFullInfo_View_001", "tbl_Report_TimeTableFullInfo_View_001"}},
			{"fGettbl_Report_TimeTableFullInfo_View_001"     , new[]{"G", "33", "33" ,"tbl_Report_TimeTableFullInfo_View_001", "tbl_Report_TimeTableFullInfo_View_001", "tbl_Report_TimeTableFullInfo_View_001"}},
			//tbl_Report_TimeTableFullInfo_View_002
			{"pGettbl_Report_TimeTableFullInfo_View_002"     , new[]{"P", "34", "34" ,"tbl_Report_TimeTableFullInfo_View_002", "tbl_Report_TimeTableFullInfo_View_002", "tbl_Report_TimeTableFullInfo_View_002"}},
			{"fGettbl_Report_TimeTableFullInfo_View_002"     , new[]{"G", "34", "34" ,"tbl_Report_TimeTableFullInfo_View_002", "tbl_Report_TimeTableFullInfo_View_002", "tbl_Report_TimeTableFullInfo_View_002"}},
			//tbl_Report_TimeTableFullInfo_View_003
			{"pGettbl_Report_TimeTableFullInfo_View_003"     , new[]{"P", "35", "35" ,"tbl_Report_TimeTableFullInfo_View_003", "tbl_Report_TimeTableFullInfo_View_003", "tbl_Report_TimeTableFullInfo_View_003"}},
			{"fGettbl_Report_TimeTableFullInfo_View_003"     , new[]{"G", "35", "35" ,"tbl_Report_TimeTableFullInfo_View_003", "tbl_Report_TimeTableFullInfo_View_003", "tbl_Report_TimeTableFullInfo_View_003"}},
			//tbl_Report_TimeTableFullInfo_View_004
			{"pGettbl_Report_TimeTableFullInfo_View_004"     , new[]{"P", "36", "36" ,"tbl_Report_TimeTableFullInfo_View_004", "tbl_Report_TimeTableFullInfo_View_004", "tbl_Report_TimeTableFullInfo_View_004"}},
			{"fGettbl_Report_TimeTableFullInfo_View_004"     , new[]{"G", "36", "36" ,"tbl_Report_TimeTableFullInfo_View_004", "tbl_Report_TimeTableFullInfo_View_004", "tbl_Report_TimeTableFullInfo_View_004"}},
			//tbl_Report_AllBranchByDate_View_005
			{"pGettbl_Report_AllBranchByDate_View_005"     , new[]{"P", "37", "37" ,"tbl_Report_AllBranchByDate_View_005", "tbl_Report_AllBranchByDate_View_005", "tbl_Report_AllBranchByDate_View_005"}},
			{"fGettbl_Report_AllBranchByDate_View_005"     , new[]{"G", "37", "37" ,"tbl_Report_AllBranchByDate_View_005", "tbl_Report_AllBranchByDate_View_005", "tbl_Report_AllBranchByDate_View_005"}},
			//tbl_Report_TimeTableFullInfo_View_005
			{"pGettbl_Report_TimeTableFullInfo_View_005"     , new[]{"P", "38", "38" ,"tbl_Report_TimeTableFullInfo_View_005", "tbl_Report_TimeTableFullInfo_View_005", "tbl_Report_TimeTableFullInfo_View_005"}},
			{"fGettbl_Report_TimeTableFullInfo_View_005"     , new[]{"G", "38", "38" ,"tbl_Report_TimeTableFullInfo_View_005", "tbl_Report_TimeTableFullInfo_View_005", "tbl_Report_TimeTableFullInfo_View_005"}},
			//tbl_Report_TimeTableFullInfo_View_001_1
			{"pGettbl_Report_TimeTableFullInfo_View_001_1"     , new[]{"P", "39", "39" ,"tbl_Report_TimeTableFullInfo_View_001_1", "tbl_Report_TimeTableFullInfo_View_001_1", "tbl_Report_TimeTableFullInfo_View_001_1"}},
			{"fGettbl_Report_TimeTableFullInfo_View_001_1"     , new[]{"G", "39", "39" ,"tbl_Report_TimeTableFullInfo_View_001_1", "tbl_Report_TimeTableFullInfo_View_001_1", "tbl_Report_TimeTableFullInfo_View_001_1"}},
			//tbl_Report_TimeTableFullInfo_View_006
			{"pGettbl_Report_TimeTableFullInfo_View_006"     , new[]{"P", "40", "40" ,"tbl_Report_TimeTableFullInfo_View_006", "tbl_Report_TimeTableFullInfo_View_006", "tbl_Report_TimeTableFullInfo_View_006"}},
			{"fGettbl_Report_TimeTableFullInfo_View_006"     , new[]{"G", "40", "40" ,"tbl_Report_TimeTableFullInfo_View_006", "tbl_Report_TimeTableFullInfo_View_006", "tbl_Report_TimeTableFullInfo_View_006"}},
			//tbl_Route_Online_View
			{"pGettbl_Route_Online_View"     , new[]{"P", "41", "41" ,"tbl_Route_Online_View", "tbl_Route_Online_View", "tbl_Route_Online_View"}},
			{"fGettbl_Route_Online_View"     , new[]{"G", "41", "41" ,"tbl_Route_Online_View", "tbl_Route_Online_View", "tbl_Route_Online_View"}},
			//tbl_Route_Online_View_001
			{"pGettbl_Route_Online_View_001"     , new[]{"P", "42", "42" ,"tbl_Route_Online_View_001", "tbl_Route_Online_View_001", "tbl_Route_Online_View_001"}},
			{"fGettbl_Route_Online_View_001"     , new[]{"G", "42", "42" ,"tbl_Route_Online_View_001", "tbl_Route_Online_View_001", "tbl_Route_Online_View_001"}},
			//tbl_Stop_View_001
			{"pGettbl_Stop_View_001"     , new[]{"P", "43", "43" ,"tbl_Stop_View_001", "tbl_Stop_View_001", "tbl_Stop_View_001"}},
			{"fGettbl_Stop_View_001"     , new[]{"G", "43", "43" ,"tbl_Stop_View_001", "tbl_Stop_View_001", "tbl_Stop_View_001"}},
			//slyt_InsertOrUpdateReportAllBranchByDate
			{"sslyt_InsertOrUpdateReportAllBranchByDate"     , new[]{"S", "44", "44" ,"slyt_InsertOrUpdateReportAllBranchByDate", "slyt_InsertOrUpdateReportAllBranchByDate", "slyt_InsertOrUpdateReportAllBranchByDate"}},
			//slyt_GetOfficeReport
			{"sslyt_GetOfficeReport"     , new[]{"S", "45", "45" ,"slyt_GetOfficeReport", "slyt_GetOfficeReport", "slyt_GetOfficeReport"}},
			//slyt_GetBranchReport
			{"sslyt_GetBranchReport"     , new[]{"S", "46", "46" ,"slyt_GetBranchReport", "slyt_GetBranchReport", "slyt_GetBranchReport"}},
			//slyt_InsertOrUpdateRouteStop
			{"sslyt_InsertOrUpdateRouteStop"     , new[]{"S", "47", "47" ,"slyt_InsertOrUpdateRouteStop", "slyt_InsertOrUpdateRouteStop", "slyt_InsertOrUpdateRouteStop"}},
			//slyt_InsertOrUpdateRouteTimeTable
			{"sslyt_InsertOrUpdateRouteTimeTable"     , new[]{"S", "48", "48" ,"slyt_InsertOrUpdateRouteTimeTable", "slyt_InsertOrUpdateRouteTimeTable", "slyt_InsertOrUpdateRouteTimeTable"}},
			//slyt_GetRouteTimeReport
			{"sslyt_GetRouteTimeReport"     , new[]{"S", "49", "49" ,"slyt_GetRouteTimeReport", "slyt_GetRouteTimeReport", "slyt_GetRouteTimeReport"}},
			//slyt_GetRouteTimeDetailReport
			{"sslyt_GetRouteTimeDetailReport"     , new[]{"S", "50", "50" ,"slyt_GetRouteTimeDetailReport", "slyt_GetRouteTimeDetailReport", "slyt_GetRouteTimeDetailReport"}},
			//slyt_InsertOrUpdateRoute
			{"sslyt_InsertOrUpdateRoute"     , new[]{"S", "51", "51" ,"slyt_InsertOrUpdateRoute", "slyt_InsertOrUpdateRoute", "slyt_InsertOrUpdateRoute"}},
			//slyt_GetRouteDepartureReport
			{"sslyt_GetRouteDepartureReport"     , new[]{"S", "52", "52" ,"slyt_GetRouteDepartureReport", "slyt_GetRouteDepartureReport", "slyt_GetRouteDepartureReport"}},
			//slyt_GetListRouteForReport
			{"sslyt_GetListRouteForReport"     , new[]{"S", "53", "53" ,"slyt_GetListRouteForReport", "slyt_GetListRouteForReport", "slyt_GetListRouteForReport"}},
			//slyt_InsertOrUpdateBranch
			{"sslyt_InsertOrUpdateBranch"     , new[]{"S", "54", "54" ,"slyt_InsertOrUpdateBranch", "slyt_InsertOrUpdateBranch", "slyt_InsertOrUpdateBranch"}},
			//slyt_InsertOrUpdateBranchOffice
			{"sslyt_InsertOrUpdateBranchOffice"     , new[]{"S", "55", "55" ,"slyt_InsertOrUpdateBranchOffice", "slyt_InsertOrUpdateBranchOffice", "slyt_InsertOrUpdateBranchOffice"}},
			//slyt_DeleteReportAllBranchByDate
			{"sslyt_DeleteReportAllBranchByDate"     , new[]{"S", "56", "56" ,"slyt_DeleteReportAllBranchByDate", "slyt_DeleteReportAllBranchByDate", "slyt_DeleteReportAllBranchByDate"}},
			//slyt_GetReportAllRouteByDate
			{"sslyt_GetReportAllRouteByDate"     , new[]{"S", "57", "57" ,"slyt_GetReportAllRouteByDate", "slyt_GetReportAllRouteByDate", "slyt_GetReportAllRouteByDate"}},
			//slyt_InsertRouteTimeTable
			{"sslyt_InsertRouteTimeTable"     , new[]{"S", "58", "58" ,"slyt_InsertRouteTimeTable", "slyt_InsertRouteTimeTable", "slyt_InsertRouteTimeTable"}},
			//slyt_DeleteRouteTimeTableByDate
			{"sslyt_DeleteRouteTimeTableByDate"     , new[]{"S", "59", "59" ,"slyt_DeleteRouteTimeTableByDate", "slyt_DeleteRouteTimeTableByDate", "slyt_DeleteRouteTimeTableByDate"}},
			//slyt_InsertOrUpdateStop
			{"sslyt_InsertOrUpdateStop"     , new[]{"S", "60", "60" ,"slyt_InsertOrUpdateStop", "slyt_InsertOrUpdateStop", "slyt_InsertOrUpdateStop"}},
		};
        //[int: 1; float: 2; string: 4; date: 5; bool: 3] [0:type, 1:isnull, 2:key, 3:fkey, 4:length, 5:ftable, 6:fId, 7:Name]
		public static Dictionary<int, string[][]> _fd = new Dictionary<int, string[][]> { 
			{27, new [] {  //tbl_Route_Stop_Exclude_View - 22 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "Id" },
				 new []{ "0", "1", "0", "", "8", "", "", "RouteId" },
				 new []{ "0", "1", "0", "", "8", "", "", "OfficeId" },
				 new []{ "22", "1", "0", "", "50", "", "", "DepartureTime" },
				 new []{ "4", "1", "0", "", "8", "", "", "DepartureDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "Address" },
				 new []{ "22", "1", "0", "", "50", "", "", "Phone" },
				 new []{ "22", "1", "0", "", "50", "", "", "Fax" },
				 new []{ "6", "1", "0", "", "8", "", "", "Latitude" },
				 new []{ "6", "1", "0", "", "8", "", "", "Longitude" },
				 new []{ "8", "1", "0", "", "4", "", "", "OrderNumber" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "12", "1", "0", "", "1024", "", "", "Note" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{28, new [] {  //tbl_Route_View_001 - 17 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "12", "1", "0", "", "256", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "OriginCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "OriginName" },
				 new []{ "22", "1", "0", "", "128", "", "", "DestCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "DestName" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSchedule" },
				 new []{ "12", "1", "0", "", "256", "", "", "Kind" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{29, new [] {  //tbl_Report_AllBranchByDate_View_001 - 5 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "IDRoute" },
				 new []{ "8", "0", "0", "", "4", "", "", "IDBranch" },
				 new []{ "4", "0", "0", "", "8", "", "", "DateStart" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalTicket" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalMoney" },
			}},
			{30, new [] {  //tbl_Report_AllBranchByDate_View_002 - 4 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "IDBranch" },
				 new []{ "4", "0", "0", "", "8", "", "", "DateStart" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalTicket" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalMoney" },
			}},
			{31, new [] {  //tbl_Report_AllBranchByDate_View_003 - 4 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "IDOffice" },
				 new []{ "4", "0", "0", "", "8", "", "", "DateStart" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalTicket" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalMoney" },
			}},
			{32, new [] {  //tbl_Report_AllBranchByDate_View_004 - 4 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "0", "0", "", "8", "", "", "DateStart" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalTicket" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalMoney" },
			}},
			{33, new [] {  //tbl_Report_TimeTableFullInfo_View_001 - 8 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "ID" },
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "128", "", "", "Time" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "22", "1", "0", "", "2", "", "", "StartHour" },
				 new []{ "22", "1", "0", "", "2", "", "", "StartMinute" },
			}},
			{34, new [] {  //tbl_Report_TimeTableFullInfo_View_002 - 8 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "ID" },
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "128", "", "", "Time" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "22", "1", "0", "", "2", "", "", "StartHour" },
				 new []{ "22", "1", "0", "", "2", "", "", "StartMinute" },
			}},
			{35, new [] {  //tbl_Report_TimeTableFullInfo_View_003 - 7 columns  
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "2", "", "", "StartHour" },
				 new []{ "22", "1", "0", "", "2", "", "", "StartMinute" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalTime" },
			}},
			{36, new [] {  //tbl_Report_TimeTableFullInfo_View_004 - 6 columns  
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "5", "", "", "Time" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalTime" },
			}},
			{37, new [] {  //tbl_Report_AllBranchByDate_View_005 - 5 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "IDRoute" },
				 new []{ "12", "1", "0", "", "512", "", "", "RouteName" },
				 new []{ "4", "0", "0", "", "8", "", "", "DateStart" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalTicket" },
				 new []{ "0", "1", "0", "", "8", "", "", "TotalMoney" },
			}},
			{38, new [] {  //tbl_Report_TimeTableFullInfo_View_005 - 7 columns  
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "5", "", "", "Time" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalTime" },
				 new []{ "12", "1", "0", "", "512", "", "", "RouteName" },
			}},
			{39, new [] {  //tbl_Report_TimeTableFullInfo_View_001_1 - 9 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "ID" },
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "128", "", "", "Time" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "22", "1", "0", "", "2", "", "", "StartHour" },
				 new []{ "22", "1", "0", "", "1", "", "", "FStartMinute" },
				 new []{ "22", "1", "0", "", "1", "", "", "LStartMinute" },
			}},
			{40, new [] {  //tbl_Report_TimeTableFullInfo_View_006 - 9 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "ID" },
				 new []{ "8", "1", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartDate" },
				 new []{ "22", "1", "0", "", "128", "", "", "Time" },
				 new []{ "12", "1", "0", "", "256", "", "", "Number" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "1", "0", "", "4", "", "", "SeatBook" },
				 new []{ "12", "1", "0", "", "512", "", "", "RouteName" },
				 new []{ "8", "1", "0", "", "4", "", "", "ReturnId" },
			}},
			{41, new [] {  //tbl_Route_Online_View - 21 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "GroupId" },
				 new []{ "8", "1", "0", "", "4", "", "", "ReturnId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "12", "1", "0", "", "256", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "OriginCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "OriginName" },
				 new []{ "22", "1", "0", "", "128", "", "", "DestCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "DestName" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "12", "1", "0", "", "256", "", "", "Kind" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSchedule" },
				 new []{ "4", "1", "0", "", "8", "", "", "StartWorkingDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "StopWorkingDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{42, new [] {  //tbl_Route_Online_View_001 - 17 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "12", "1", "0", "", "256", "", "", "Code" },
				 new []{ "12", "1", "0", "", "512", "", "", "Name" },
				 new []{ "22", "1", "0", "", "128", "", "", "OriginCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "OriginName" },
				 new []{ "22", "1", "0", "", "128", "", "", "DestCode" },
				 new []{ "12", "1", "0", "", "512", "", "", "DestName" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "8", "1", "0", "", "4", "", "", "TotalSchedule" },
				 new []{ "12", "1", "0", "", "256", "", "", "Kind" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
			}},
			{43, new [] {  //tbl_Stop_View_001 - 25 columns  
				 new []{ "0", "0", "0", "", "8", "", "", "Id" },
				 new []{ "8", "1", "0", "", "4", "", "", "RouteId" },
				 new []{ "8", "1", "0", "", "4", "", "", "WayId" },
				 new []{ "8", "1", "0", "", "4", "", "", "OfficeId" },
				 new []{ "8", "1", "0", "", "4", "", "", "Type" },
				 new []{ "22", "1", "0", "", "128", "", "", "Code" },
				 new []{ "12", "1", "0", "", "256", "", "", "Name" },
				 new []{ "12", "1", "0", "", "512", "", "", "Address" },
				 new []{ "22", "1", "0", "", "50", "", "", "Phone" },
				 new []{ "22", "1", "0", "", "50", "", "", "Fax" },
				 new []{ "6", "1", "0", "", "8", "", "", "Latitude" },
				 new []{ "6", "1", "0", "", "8", "", "", "Longitude" },
				 new []{ "8", "1", "0", "", "4", "", "", "OrderNumber" },
				 new []{ "8", "1", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "1", "0", "", "4", "", "", "Duration" },
				 new []{ "2", "1", "0", "", "1", "", "", "Passing" },
				 new []{ "8", "1", "0", "", "4", "", "", "ShuttleBefore" },
				 new []{ "12", "1", "0", "", "1024", "", "", "Note" },
				 new []{ "8", "1", "0", "", "4", "", "", "Status" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgCreatedDate" },
				 new []{ "4", "1", "0", "", "8", "", "", "IsPrgUpdatedDate" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgCreatedUserId" },
				 new []{ "8", "1", "0", "", "4", "", "", "IsPrgUpdatedUserId" },
				 new []{ "22", "1", "0", "", "128", "", "", "OriginCode" },
				 new []{ "22", "1", "0", "", "128", "", "", "DestCode" },
			}},
			{44, new [] {  //slyt_InsertOrUpdateReportAllBranchByDate - 6 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "IDRoute" },
				 new []{ "8", "0", "0", "", "4", "", "", "IDBranch" },
				 new []{ "8", "0", "0", "", "4", "", "", "IDOffice" },
				 new []{ "4", "0", "0", "", "8", "", "", "DateStart" },
				 new []{ "8", "0", "0", "", "4", "", "", "TotalTicket" },
				 new []{ "8", "0", "0", "", "4", "", "", "TotalMoney" },
			}},
			{45, new [] {  //slyt_GetOfficeReport - 2 columns  
				 new []{ "4", "0", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "0", "0", "", "8", "", "", "ToDate" },
			}},
			{46, new [] {  //slyt_GetBranchReport - 2 columns  
				 new []{ "4", "0", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "0", "0", "", "8", "", "", "ToDate" },
			}},
			{47, new [] {  //slyt_InsertOrUpdateRouteStop - 8 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "Type" },
				 new []{ "8", "0", "0", "", "4", "", "", "OfficeId" },
				 new []{ "8", "0", "0", "", "4", "", "", "RouteId" },
				 new []{ "22", "0", "0", "", "128", "", "", "Code" },
				 new []{ "12", "0", "0", "", "512", "", "", "Name" },
				 new []{ "12", "0", "0", "", "1024", "", "", "Address" },
				 new []{ "12", "0", "0", "", "512", "", "", "Phone" },
				 new []{ "12", "0", "0", "", "512", "", "", "Fax" },
			}},
			{48, new [] {  //slyt_InsertOrUpdateRouteTimeTable - 13 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "ID" },
				 new []{ "8", "0", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "0", "0", "", "8", "", "", "StartDate" },
				 new []{ "12", "0", "0", "", "100", "", "", "Time" },
				 new []{ "12", "0", "0", "", "100", "", "", "Number" },
				 new []{ "12", "0", "0", "", "100", "", "", "FullName" },
				 new []{ "12", "0", "0", "", "100", "", "", "FirstName" },
				 new []{ "12", "0", "0", "", "100", "", "", "Phone" },
				 new []{ "12", "0", "0", "", "100", "", "", "FullName2" },
				 new []{ "12", "0", "0", "", "100", "", "", "FirstName2" },
				 new []{ "12", "0", "0", "", "100", "", "", "Phone2" },
				 new []{ "8", "0", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "0", "0", "", "4", "", "", "SeatBook" },
			}},
			{49, new [] {  //slyt_GetRouteTimeReport - 3 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "RouteId" },
				 new []{ "4", "0", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "0", "0", "", "8", "", "", "ToDate" },
			}},
			{50, new [] {  //slyt_GetRouteTimeDetailReport - 4 columns  
				 new []{ "22", "0", "0", "", "128", "", "", "Time" },
				 new []{ "8", "0", "0", "", "4", "", "", "RouteId" },
				 new []{ "4", "0", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "0", "0", "", "8", "", "", "ToDate" },
			}},
			{51, new [] {  //slyt_InsertOrUpdateRoute - 3 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "Id" },
				 new []{ "12", "0", "0", "", "256", "", "", "Code" },
				 new []{ "12", "0", "0", "", "512", "", "", "Name" },
			}},
			{52, new [] {  //slyt_GetRouteDepartureReport - 1 columns  
				 new []{ "4", "0", "0", "", "8", "", "", "DepartureDate" },
			}},
			{53, new [] {  //slyt_GetListRouteForReport - 2 columns  
				 new []{ "4", "0", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "0", "0", "", "8", "", "", "ToDate" },
			}},
			{54, new [] {  //slyt_InsertOrUpdateBranch - 2 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "Id" },
				 new []{ "12", "0", "0", "", "512", "", "", "Name" },
			}},
			{55, new [] {  //slyt_InsertOrUpdateBranchOffice - 3 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "Id" },
				 new []{ "8", "0", "0", "", "4", "", "", "BranchId" },
				 new []{ "12", "0", "0", "", "512", "", "", "Name" },
			}},
			{56, new [] {  //slyt_DeleteReportAllBranchByDate - 2 columns  
				 new []{ "4", "0", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "0", "0", "", "8", "", "", "ToDate" },
			}},
			{57, new [] {  //slyt_GetReportAllRouteByDate - 2 columns  
				 new []{ "4", "0", "0", "", "8", "", "", "FromDate" },
				 new []{ "4", "0", "0", "", "8", "", "", "ToDate" },
			}},
			{58, new [] {  //slyt_InsertRouteTimeTable - 7 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "ID" },
				 new []{ "8", "0", "0", "", "4", "", "", "IDRoute" },
				 new []{ "4", "0", "0", "", "8", "", "", "StartDate" },
				 new []{ "12", "0", "0", "", "100", "", "", "Time" },
				 new []{ "12", "0", "0", "", "100", "", "", "Number" },
				 new []{ "8", "0", "0", "", "4", "", "", "TotalSeat" },
				 new []{ "8", "0", "0", "", "4", "", "", "SeatBook" },
			}},
			{59, new [] {  //slyt_DeleteRouteTimeTableByDate - 1 columns  
				 new []{ "4", "0", "0", "", "8", "", "", "DepartureDate" },
			}},
			{60, new [] {  //slyt_InsertOrUpdateStop - 11 columns  
				 new []{ "8", "0", "0", "", "4", "", "", "RouteId" },
				 new []{ "8", "0", "0", "", "4", "", "", "WayId" },
				 new []{ "8", "0", "0", "", "4", "", "", "OfficeId" },
				 new []{ "8", "0", "0", "", "4", "", "", "Type" },
				 new []{ "12", "0", "0", "", "256", "", "", "Name" },
				 new []{ "12", "0", "0", "", "512", "", "", "Address" },
				 new []{ "8", "0", "0", "", "4", "", "", "Distance" },
				 new []{ "8", "0", "0", "", "4", "", "", "Duration" },
				 new []{ "2", "0", "0", "", "1", "", "", "Passing" },
				 new []{ "8", "0", "0", "", "4", "", "", "ShuttleBefore" },
				 new []{ "12", "0", "0", "", "1024", "", "", "Note" },
			}},
		};
    }
}