///////////////////////////////////////////////////////////
//  CoreJava.cs
//  Implementation of the Class CoreJava
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

namespace CTool.Builder.Java
{
    public class CoreJava : ILanguage
    {
        public CoreJava()
        {
        }

        ~CoreJava()
        {
        }

        public void WriteIf()
        {
        }

        public void WriteFor()
        {
        }
    }
} //end CoreJava