///////////////////////////////////////////////////////////
//  IBuilder.cs
//  Implementation of the Interface IBuilder
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

namespace CTool.Builder
{
    public interface IBuilder
    {
        /// 
        /// <param name="appId"></param>
        void BuildApp(int appId);

        /// 
        /// <param name="pageId"></param>
        /// <param name="nameSpace"></param>
        void BuildPage(int pageId, string nameSpace);

        /// 
        /// <param name="pageId"></param>
        string BuildCodeBehind(int pageId);

        /// 
        /// <param name="pageId"></param>
        string BuildJS(int pageId);

        /// 
        /// <param name="templateId"></param>
        string BuildTemplate(int templateId);
    }
} //end IBuilder