///////////////////////////////////////////////////////////
//  ICoreForm.cs
//  Implementation of the Interface ICoreForm
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

namespace CTool.Builder
{
    public interface ICoreForm
    {
        /// 
        /// <param name="codeTemplateId"></param>
        /// <param name="value"></param>
        string GenAssignCode(int codeTemplateId, string value);
    }
} //end ICoreForm