///////////////////////////////////////////////////////////
//  ILanguage.cs
//  Implementation of the Interface ILanguage
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

namespace CTool.Builder
{
    public interface ILanguage
    {
        void WriteIf();

        void WriteFor();
    }
} //end ILanguage