///////////////////////////////////////////////////////////
//  CoreCSharp.cs
//  Implementation of the Class CoreCSharp
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CoreCSharp : ILanguage {

	public CoreCSharp(){

	}

	~CoreCSharp(){

	}

	public void WriteIf(){

	}

	public void WriteFor(){

	}

}//end CoreCSharp