///////////////////////////////////////////////////////////
//  CoreWebForm.cs
//  Implementation of the Class CoreWebForm
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CoreWebForm : ICoreForm {

	public CoreWebForm(){

	}

	~CoreWebForm(){

	}

	/// 
	/// <param name="CodeTemplateId"></param>
	/// <param name="Value"></param>
	public string GenAssignCode(int CodeTemplateId, string Value){

		return "";
	}

}//end CoreWebForm