///////////////////////////////////////////////////////////
//  DotNetWebFormBuilder.cs
//  Implementation of the Class DotNetWebFormBuilder
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DotNetWebFormBuilder : IBuilder {

	public DotNetWebFormBuilder(){

	}

	~DotNetWebFormBuilder(){

	}

	/// 
	/// <param name="AppId"></param>
	public void BuildApp(int AppId){

	}

	/// 
	/// <param name="TemplateId"></param>
	public string BuildTemplate(int TemplateId){

		return "";
	}

	/// 
	/// <param name="PageId"></param>
	public void BuildPage(int PageId){

	}

	/// 
	/// <param name="PageId"></param>
	public string BuildCodeBehind(int PageId){

		return "";
	}

	/// 
	/// <param name="PageId"></param>
	public string BuildJS(int PageId){

		return "";
	}

}//end DotNetWebFormBuilder