///////////////////////////////////////////////////////////
//  FileWriter.cs
//  Implementation of the Class FileWriter
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class FileWriter {

	public FileWriter(){

	}

	~FileWriter(){

	}

	/// 
	/// <param name="content"></param>
	/// <param name="path"></param>
	public bool WriteFile(string content, string path){

		string[] lines = { "First line", "Second line", "Third line" };
		 // WriteAllLines creates a file, writes a collection of strings to the file, 
		 // and then closes the file.
		 System.IO.File.WriteAllLines(@"C:\Users\Public\TestFolder\WriteLines.txt", lines);
	}

}//end FileWriter