///////////////////////////////////////////////////////////
//  IBuilder.cs
//  Implementation of the Interface IBuilder
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IBuilder  {

	/// 
	/// <param name="AppId"></param>
	void BuildApp(int AppId);

	/// 
	/// <param name="PageId"></param>
	void BuildPage(int PageId);

	/// 
	/// <param name="PageId"></param>
	string BuildCodeBehind(int PageId);

	/// 
	/// <param name="PageId"></param>
	string BuildJS(int PageId);

	/// 
	/// <param name="TemplateId"></param>
	string BuildTemplate(int TemplateId);
}//end IBuilder