///////////////////////////////////////////////////////////
//  ICoreForm.cs
//  Implementation of the Interface ICoreForm
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICoreForm  {

	/// 
	/// <param name="CodeTemplateId"></param>
	/// <param name="Value"></param>
	string GenAssignCode(int CodeTemplateId, string Value);
}//end ICoreForm