///////////////////////////////////////////////////////////
//  Service.cs
//  Implementation of the Class Service
//  Generated by Enterprise Architect
//  Created on:      15-Dec-2014 3:35:21 PM
//  Original author: baovan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Service {

	public Service(){

	}

	~Service(){

	}

	/// 
	/// <param name="o"></param>
	public object P(object o){

		return null;
	}

}//end Service